version: '3'
services:
  nginx-splash:
    image: anthonymejia/nginx-splash
    ports:
      - "80:80"
    environment:
      VIRTUAL_HOST: 'home'
      DEFAULT_HOST: 'home'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: ${PI_PASSWORD}
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.nuc.lan
      VIRTUAL_PORT: 80
      SPLASH_ICON: medium_priority.svg
      SPLASH_NAME: PiHole
    volumes:
      - ${CONFIG_DIR-/config}/etc-pihole/:/etc/pihole/
      - ${CONFIG_DIR-/config}/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1

  plex:
    image: linuxserver/plex
    container_name: plex
    restart: always
    environment:
      VERSION: docker
      PLEX_CLAIM: ${PLEX_CLAIM}
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'
      VIRTUAL_HOST: 'plex.nuc.lan'
      VIRTUAL_PORT: 32400
      SPLASH_ICON: video_projector.svg
      SPLASH_NAME: Plex
    volumes:
      - ${CONFIG_DIR-/config}/plex/config:/config
      - ${DATA_DIR-/data}/transmission:/data
      - ${CONFIG_DIR-/config}/plex/transcode:/transcode
    ports:
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 32469:32469
      - 1900:1900
      - 32410:32410
      - 32412:32412
      - 32413:32413
      - 32414:32414

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'
      VIRTUAL_HOST: 'sonar.nuc.lan'
      SPLASH_ICON: conference_call.svg
      SPLASH_NAME: Sonar
    volumes:
      - ${CONFIG_DIR-/config}/sonarr/config:/config
      - ${DATA_DIR-/data}/transmission/completed:/downloads
    ports:
      - 8989:8989

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: 'America/New_York'
      VIRTUAL_HOST: 'radar.nuc.lan'
      SPLASH_ICON: film_reel.svg
      SPLASH_NAME: Radar
    volumes:
      - ${CONFIG_DIR-/config}/radarr/config:/config
      - ${DATA_DIR-/data}/transmission/completed:/downloads
    ports:
      - 7878:7878

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    environment:
      PGID: 1000
      PUID: 1000
      TZ: 'America/New_York'
      VIRTUAL_HOST: 'jacket.nuc.lan'
      SPLASH_ICON: search.svg
      SPLASH_NAME: Jacket
    volumes:
      - ${CONFIG_DIR-/config}/jackett/config:/config
      - ${CONFIG_DIR-/config}/jackett/downloads:/downloads
    ports:
      - 9117:9117

  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      CREATE_TUN_DEVICE: "true"
      TRANSMISSION_SPEED_LIMIT_UP: 1
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
      TRANSMISSION_RATIO_LIMIT: 0.0001
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_IDLE_SEEDING_LIMIT: 5
      TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED: "true"
      TRANSMISSION_UTP_ENABLED: "false"
      OPENVPN_PROVIDER: ${VPN_PROVIDER}
      OPENVPN_USERNAME: ${VPN_USERNAME}
      OPENVPN_PASSWORD: ${VPN_PASSWORD}
      OPENVPN_CONFIG: ${VPN_CONFIG}
      LOCAL_NETWORK: ${LOCAL_NETWORK}
      TRANSMISSION_WEB_UI: "combustion"
      VIRTUAL_HOST: 'transmission.nuc.lan'
      VIRTUAL_PORT: 9091
      SPLASH_ICON: internal.svg
      SPLASH_NAME: Transmission
    volumes:
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR-/data}/transmission:/data
    ports:
      - 9091:9091
      - 42424:42424
